# Central configuration for the minimal FSL-EC project

embedding:
  model: esm2_t12_35M_UR50D  # ESM2-t12-35M (UR50D)
  # limit removed for full run (set 'limit: 1000' temporarily for smoke tests)

# Device selection: "auto" → cuda if available else cpu
device: auto

# Episode settings
episode:
  M: 10              # ways
  K_train: 5         # shots for training episodes
  K_eval: [1, 5]     # shots for evaluation episodes
  Q: 10              # queries per class

# Number of episodes
episodes:
  train: 1000
  val: 200

# Embedding
batch_size_embed: 64  # raise to 128–512 on A40 (use config.hpc.yaml)
max_seq_len: 1022     # full ESM2 context window
fp16: true            # enable FP16 inference on GPU
dynamic_batch: true   # reduce batch size automatically on OOM
progress: true
verbose: false

# Training knobs
fp16_train: false           # AMP for ProtoNet head (usually not needed)
eval_every: 100             # episodes between validations (auto if unset)
episodes_per_val_check: 50  # validation episodes per check

# ProtoNet head
projection_dim: 256
temperature: 10.0

# Data filtering and splits
min_sequences_per_class_for_train: 40  # classes with < this go to meta-test pool
random_seed: 42

# Paths
paths:
  data_root: data/uniprot_ec
  joined_tsv: data/uniprot_ec/swissprot_ec_joined.tsv
  embeddings: data/emb/embeddings.npz
  splits_dir: data/splits
  outputs: results
